name: Node CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # Install dependencies
    - run: npm ci
    # Make sure that it can build
    - run: npm run build
    # Run tests
    - run: npm test
    - name: codecov
      run: npx codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
